// S&P 500 constituents, sourced from the Wikipedia-mirrored dataset at
// https://github.com/datasets/s-and-p-500-companies (auto-refreshed daily
// upstream; snapshotted here as of the date below since the optimizer
// needs a stable, versioned universe rather than a live fetch every run).
//
// Known v1 limitation: this is the *current* constituent list applied
// retroactively across all historical date ranges -- see README.md.
//
// Two symbols use a dot for share class (BRK.B, BF.B) -- the Yahoo data
// client (see yahoo-client.ts) maps these to Yahoo's own symbol format
// (a hyphen instead of a dot, e.g. BRK-B).
//
// Refresh: re-fetch data/constituents.csv from the source repo above and
// regenerate this file, or ask Claude to refresh it.
//
// Snapshot date: 2026-08-20
//
// -- weight field (issue #230) --
//
// `weight` is State Street's own published SPY (SPDR S&P 500 ETF Trust)
// holdings percentage for each ticker, as-sourced with no recomputation --
// not a separately-derived market-cap number (which could drift out of
// sync with the source) and not a stored rank (rank is a derived,
// display-only sort over `weight`, computed on demand wherever needed,
// e.g. `[...SP500_CONSTITUENTS].sort((a, b) => b.weight - a.weight)`, so
// it can never disagree with `weight` after a partial refresh).
//
// Source verified live before committing to it, the same empirical bar
// the Yahoo-vs-Stooq decision used (see this package's own CLAUDE.md
// "Data source" section): SSGA's holdings file at
// https://www.ssga.com/us/en/intermediary/library-content/products/fund-data/etfs/us/holdings-daily-us-en-spy.xlsx
// downloads as a plain, unauthenticated GET -- HTTP 200, a real .xlsx
// spreadsheet (not scraped HTML), no bot-blocking, no browser-like
// `User-Agent` even required (unlike Yahoo's chart endpoint). No CSV
// variant of this file exists at SSGA (a `.csv` extension 404s); `.xlsx`
// is what SSGA actually publishes, so that's what was fetched and parsed
// for this snapshot. iShares' IVV holdings endpoint, checked as the
// issue's suggested cross-check, does NOT clear this same bar as of this
// writing: despite an advertised `Content-Type: text/csv`, a plain GET to
// its `.ajax?fileType=csv` URL returns an HTML interstitial page, not
// holdings data -- so IVV was not used for this snapshot; SSGA was the
// only source of the two that actually verified live as a plain download.
//
// Snapshot date/source: SSGA SPY holdings "As of 09-Sep-2026", fetched
// 2026-09-10. All 503 of this file's existing symbols matched an SSGA
// ticker exactly (including both dot-suffixed share classes, BRK.B and
// BF.B -- SSGA already publishes these with the same dot convention this
// file uses, so no symbol translation was needed for this join, unlike
// `toYahooSymbol()`'s dot-to-hyphen mapping for Yahoo). Weights sum to
// ~99.78% across these 503 symbols (SPY's published weights for its full
// ~505-line holdings file sum to ~99.95%; the remainder is cash/other and
// a couple of non-S&P-500 residual/legacy lines SPY still carries, e.g. a
// tiny post-acquisition holdover position, which this file's 503-symbol
// universe correctly excludes).
//
// Refresh process: re-fetch the SSGA URL above, parse its "Name" / "Ticker"
// / "Weight" columns, and join by ticker onto this file's existing
// `symbol` list (or ask Claude to refresh it) -- same manual cadence as
// the rest of this file, not a live/nightly fetch (explicitly out of
// scope for issue #230).
//
// Retroactive-application caveat (stronger than the plain membership/rank
// limitation above): applying today's *weight* across a multi-year
// historical window is a bigger simplification than applying today's mere
// membership/rank retroactively. Rank and membership can go years without
// changing; weight drifts continuously -- every trading day, even for a
// stable membership/rank -- since it tracks real-time market
// capitalization. Any consumer of this field (e.g. "The Cut", see
// `docs/design/the-cut-2026-09/README.md`) that renormalizes these
// weights across a historical window is therefore working from a materially
// larger point-in-time departure than this file's existing constituent-list
// limitation alone. Not investment advice, not a predictor -- see this
// repo's root README for the app's overall "retrospective toy" framing.

export interface SP500Constituent {
  /** Ticker symbol as commonly quoted, e.g. "AAPL", "BRK.B". */
  symbol: string;
  /** Company name. */
  name: string;
  /** GICS sector. */
  sector: string;
  /**
   * Real S&P 500 index-weight magnitude (SSGA's published SPY holdings
   * percentage, as-sourced -- see this file's header comment for the
   * source, snapshot date, and the larger-than-usual retroactive-
   * application caveat). A raw percentage point value (e.g. `7.036031`
   * means ~7.04%), not a 0-1 fraction and not a rank.
   */
  weight: number;
}

export const SP500_CONSTITUENTS: SP500Constituent[] = [
  { symbol: "MMM", name: "3M", sector: "Industrials", weight: 0.130393 },
  { symbol: "AOS", name: "A. O. Smith", sector: "Industrials", weight: 0.009843 },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Health Care", weight: 0.278384 },
  { symbol: "ABBV", name: "AbbVie", sector: "Health Care", weight: 0.673314 },
  { symbol: "ACN", name: "Accenture", sector: "Information Technology", weight: 0.163779 },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "Information Technology", weight: 0.156303 },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices",
    sector: "Information Technology",
    weight: 1.290753,
  },
  { symbol: "AES", name: "AES Corporation", sector: "Utilities", weight: 0.016072 },
  { symbol: "AFL", name: "Aflac", sector: "Financials", weight: 0.079927 },
  { symbol: "A", name: "Agilent Technologies", sector: "Health Care", weight: 0.062213 },
  { symbol: "APD", name: "Air Products", sector: "Materials", weight: 0.100014 },
  { symbol: "ABNB", name: "Airbnb", sector: "Consumer Discretionary", weight: 0.107808 },
  {
    symbol: "AKAM",
    name: "Akamai Technologies",
    sector: "Information Technology",
    weight: 0.024484,
  },
  { symbol: "ALB", name: "Albemarle Corporation", sector: "Materials", weight: 0.02255 },
  {
    symbol: "ARE",
    name: "Alexandria Real Estate Equities",
    sector: "Real Estate",
    weight: 0.011963,
  },
  { symbol: "ALGN", name: "Align Technology", sector: "Health Care", weight: 0.015325 },
  { symbol: "ALLE", name: "Allegion", sector: "Industrials", weight: 0.019606 },
  { symbol: "LNT", name: "Alliant Energy", sector: "Utilities", weight: 0.026505 },
  { symbol: "ALL", name: "Allstate", sector: "Financials", weight: 0.099265 },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc. (Class A)",
    sector: "Communication Services",
    weight: 2.945484,
  },
  {
    symbol: "GOOG",
    name: "Alphabet Inc. (Class C)",
    sector: "Communication Services",
    weight: 2.357876,
  },
  { symbol: "MO", name: "Altria", sector: "Consumer Staples", weight: 0.172032 },
  { symbol: "AMZN", name: "Amazon", sector: "Consumer Discretionary", weight: 3.753636 },
  { symbol: "AMCR", name: "Amcor", sector: "Materials", weight: 0.030114 },
  { symbol: "AEE", name: "Ameren", sector: "Utilities", weight: 0.044703 },
  { symbol: "AEP", name: "American Electric Power", sector: "Utilities", weight: 0.103154 },
  { symbol: "AXP", name: "American Express", sector: "Financials", weight: 0.260107 },
  { symbol: "AIG", name: "American International Group", sector: "Financials", weight: 0.060495 },
  { symbol: "AMT", name: "American Tower", sector: "Real Estate", weight: 0.124294 },
  { symbol: "AWK", name: "American Water Works", sector: "Utilities", weight: 0.041671 },
  { symbol: "AMP", name: "Ameriprise Financial", sector: "Financials", weight: 0.075443 },
  { symbol: "AME", name: "Ametek", sector: "Industrials", weight: 0.08236 },
  { symbol: "AMGN", name: "Amgen", sector: "Health Care", weight: 0.32083 },
  { symbol: "APH", name: "Amphenol", sector: "Information Technology", weight: 0.303979 },
  { symbol: "ADI", name: "Analog Devices", sector: "Information Technology", weight: 0.270688 },
  { symbol: "AON", name: "Aon plc", sector: "Financials", weight: 0.098969 },
  { symbol: "APA", name: "APA Corporation", sector: "Energy", weight: 0.024104 },
  { symbol: "APO", name: "Apollo Global Management", sector: "Financials", weight: 0.091865 },
  { symbol: "AAPL", name: "Apple Inc.", sector: "Information Technology", weight: 7.036031 },
  { symbol: "AMAT", name: "Applied Materials", sector: "Information Technology", weight: 0.565351 },
  { symbol: "APP", name: "AppLovin", sector: "Communication Services", weight: 0.124818 },
  { symbol: "APTV", name: "Aptiv", sector: "Consumer Discretionary", weight: 0.014342 },
  { symbol: "ACGL", name: "Arch Capital Group", sector: "Financials", weight: 0.050868 },
  { symbol: "ADM", name: "Archer Daniels Midland", sector: "Consumer Staples", weight: 0.06343 },
  { symbol: "ARES", name: "Ares Management", sector: "Financials", weight: 0.043098 },
  { symbol: "ANET", name: "Arista Networks", sector: "Information Technology", weight: 0.30257 },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co.", sector: "Financials", weight: 0.095439 },
  { symbol: "AIZ", name: "Assurant", sector: "Financials", weight: 0.02114 },
  { symbol: "T", name: "AT&T", sector: "Communication Services", weight: 0.265387 },
  { symbol: "ATO", name: "Atmos Energy", sector: "Utilities", weight: 0.042064 },
  { symbol: "ADSK", name: "Autodesk", sector: "Information Technology", weight: 0.066339 },
  { symbol: "ADP", name: "Automatic Data Processing", sector: "Industrials", weight: 0.160878 },
  { symbol: "AZO", name: "AutoZone", sector: "Consumer Discretionary", weight: 0.072904 },
  { symbol: "AVY", name: "Avery Dennison", sector: "Materials", weight: 0.019745 },
  { symbol: "AXON", name: "Axon Enterprise", sector: "Industrials", weight: 0.060075 },
  { symbol: "BKR", name: "Baker Hughes", sector: "Energy", weight: 0.096029 },
  { symbol: "BALL", name: "Ball Corporation", sector: "Materials", weight: 0.024409 },
  { symbol: "BAC", name: "Bank of America", sector: "Financials", weight: 0.62145 },
  { symbol: "BAX", name: "Baxter International", sector: "Health Care", weight: 0.019244 },
  { symbol: "BDX", name: "Becton Dickinson", sector: "Health Care", weight: 0.075346 },
  { symbol: "BRK.B", name: "Berkshire Hathaway", sector: "Financials", weight: 1.411229 },
  { symbol: "BBY", name: "Best Buy", sector: "Consumer Discretionary", weight: 0.026323 },
  { symbol: "TECH", name: "Bio-Techne", sector: "Health Care", weight: 0.017232 },
  { symbol: "BIIB", name: "Biogen", sector: "Health Care", weight: 0.047384 },
  { symbol: "BLK", name: "BlackRock", sector: "Financials", weight: 0.235033 },
  { symbol: "BX", name: "Blackstone Inc.", sector: "Financials", weight: 0.145494 },
  { symbol: "XYZ", name: "Block, Inc.", sector: "Financials", weight: 0.064623 },
  { symbol: "BNY", name: "BNY Mellon", sector: "Financials", weight: 0.169268 },
  { symbol: "BA", name: "Boeing", sector: "Industrials", weight: 0.247137 },
  { symbol: "BKNG", name: "Booking Holdings", sector: "Consumer Discretionary", weight: 0.204083 },
  { symbol: "BSX", name: "Boston Scientific", sector: "Health Care", weight: 0.101625 },
  { symbol: "BMY", name: "Bristol Myers Squibb", sector: "Health Care", weight: 0.199629 },
  { symbol: "AVGO", name: "Broadcom", sector: "Information Technology", weight: 2.620959 },
  { symbol: "BR", name: "Broadridge Financial Solutions", sector: "Industrials", weight: 0.029565 },
  { symbol: "BRO", name: "Brown & Brown", sector: "Financials", weight: 0.029492 },
  { symbol: "BF.B", name: "Brown–Forman", sector: "Consumer Staples", weight: 0.006697 },
  { symbol: "BLDR", name: "Builders FirstSource", sector: "Industrials", weight: 0.01004 },
  { symbol: "BG", name: "Bunge Global", sector: "Consumer Staples", weight: 0.025587 },
  { symbol: "BXP", name: "BXP, Inc.", sector: "Real Estate", weight: 0.014449 },
  { symbol: "CHRW", name: "C.H. Robinson", sector: "Industrials", weight: 0.026965 },
  {
    symbol: "CDNS",
    name: "Cadence Design Systems",
    sector: "Information Technology",
    weight: 0.119379,
  },
  { symbol: "CPT", name: "Camden Property Trust", sector: "Real Estate", weight: 0.015912 },
  { symbol: "COF", name: "Capital One", sector: "Financials", weight: 0.199236 },
  { symbol: "CAH", name: "Cardinal Health", sector: "Health Care", weight: 0.085488 },
  {
    symbol: "CCL",
    name: "Carnival Corporation",
    sector: "Consumer Discretionary",
    weight: 0.044254,
  },
  { symbol: "CARR", name: "Carrier Global", sector: "Industrials", weight: 0.068802 },
  { symbol: "CVNA", name: "Carvana", sector: "Consumer Discretionary", weight: 0.079964 },
  { symbol: "CASY", name: "Casey's", sector: "Consumer Staples", weight: 0.035405 },
  { symbol: "CAT", name: "Caterpillar Inc.", sector: "Industrials", weight: 0.570519 },
  { symbol: "CBOE", name: "Cboe Global Markets", sector: "Financials", weight: 0.046544 },
  { symbol: "CBRE", name: "CBRE Group", sector: "Real Estate", weight: 0.062203 },
  { symbol: "CDW", name: "CDW Corporation", sector: "Information Technology", weight: 0.027659 },
  { symbol: "COR", name: "Cencora", sector: "Health Care", weight: 0.095672 },
  { symbol: "CNC", name: "Centene Corporation", sector: "Health Care", weight: 0.045636 },
  { symbol: "CNP", name: "CenterPoint Energy", sector: "Utilities", weight: 0.039549 },
  { symbol: "CF", name: "CF Industries", sector: "Materials", weight: 0.032267 },
  { symbol: "CRL", name: "Charles River Laboratories", sector: "Health Care", weight: 0.02039 },
  { symbol: "SCHW", name: "Charles Schwab Corporation", sector: "Financials", weight: 0.264517 },
  {
    symbol: "CHTR",
    name: "Charter Communications",
    sector: "Communication Services",
    weight: 0.02324,
  },
  { symbol: "CVX", name: "Chevron Corporation", sector: "Energy", weight: 0.607923 },
  {
    symbol: "CMG",
    name: "Chipotle Mexican Grill",
    sector: "Consumer Discretionary",
    weight: 0.070283,
  },
  { symbol: "CB", name: "Chubb Limited", sector: "Financials", weight: 0.184824 },
  { symbol: "CHD", name: "Church & Dwight", sector: "Consumer Staples", weight: 0.034212 },
  { symbol: "CIEN", name: "Ciena", sector: "Information Technology", weight: 0.072517 },
  { symbol: "CI", name: "Cigna", sector: "Health Care", weight: 0.111896 },
  { symbol: "CINF", name: "Cincinnati Financial", sector: "Financials", weight: 0.039811 },
  { symbol: "CTAS", name: "Cintas", sector: "Industrials", weight: 0.103197 },
  { symbol: "CSCO", name: "Cisco", sector: "Information Technology", weight: 0.656503 },
  { symbol: "C", name: "Citigroup", sector: "Financials", weight: 0.356885 },
  { symbol: "CFG", name: "Citizens Financial Group", sector: "Financials", weight: 0.044611 },
  { symbol: "CLX", name: "Clorox", sector: "Consumer Staples", weight: 0.016569 },
  { symbol: "CME", name: "CME Group", sector: "Financials", weight: 0.151014 },
  { symbol: "CMS", name: "CMS Energy", sector: "Utilities", weight: 0.031878 },
  { symbol: "KO", name: "Coca-Cola Company (The)", sector: "Consumer Staples", weight: 0.514832 },
  { symbol: "CTSH", name: "Cognizant", sector: "Information Technology", weight: 0.041943 },
  { symbol: "COHR", name: "Coherent Corp.", sector: "Information Technology", weight: 0.090279 },
  { symbol: "COIN", name: "Coinbase", sector: "Financials", weight: 0.059101 },
  { symbol: "CL", name: "Colgate-Palmolive", sector: "Consumer Staples", weight: 0.107126 },
  { symbol: "CMCSA", name: "Comcast", sector: "Communication Services", weight: 0.133232 },
  { symbol: "FIX", name: "Comfort Systems USA", sector: "Industrials", weight: 0.086265 },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energy", weight: 0.252585 },
  { symbol: "ED", name: "Consolidated Edison", sector: "Utilities", weight: 0.06025 },
  { symbol: "STZ", name: "Constellation Brands", sector: "Consumer Staples", weight: 0.02578 },
  { symbol: "CEG", name: "Constellation Energy", sector: "Utilities", weight: 0.142876 },
  { symbol: "COO", name: "Cooper Companies (The)", sector: "Health Care", weight: 0.018831 },
  { symbol: "CPRT", name: "Copart", sector: "Industrials", weight: 0.04317 },
  { symbol: "GLW", name: "Corning Inc.", sector: "Information Technology", weight: 0.200245 },
  { symbol: "CPAY", name: "Corpay", sector: "Financials", weight: 0.04037 },
  { symbol: "CTVA", name: "Corteva", sector: "Materials", weight: 0.086203 },
  { symbol: "CSGP", name: "CoStar Group", sector: "Real Estate", weight: 0.018371 },
  { symbol: "COST", name: "Costco", sector: "Consumer Staples", weight: 0.608203 },
  { symbol: "CRH", name: "CRH plc", sector: "Materials", weight: 0.090792 },
  { symbol: "CRWD", name: "CrowdStrike", sector: "Information Technology", weight: 0.321376 },
  { symbol: "CCI", name: "Crown Castle", sector: "Real Estate", weight: 0.049986 },
  { symbol: "CSX", name: "CSX Corporation", sector: "Industrials", weight: 0.136684 },
  { symbol: "CMI", name: "Cummins", sector: "Industrials", weight: 0.116415 },
  { symbol: "CVS", name: "CVS Health", sector: "Health Care", weight: 0.184696 },
  { symbol: "DHR", name: "Danaher Corporation", sector: "Health Care", weight: 0.195842 },
  { symbol: "DRI", name: "Darden Restaurants", sector: "Consumer Discretionary", weight: 0.036469 },
  { symbol: "DDOG", name: "Datadog", sector: "Information Technology", weight: 0.113341 },
  { symbol: "DVA", name: "DaVita", sector: "Health Care", weight: 0.00894 },
  { symbol: "DECK", name: "Deckers Brands", sector: "Consumer Discretionary", weight: 0.017257 },
  { symbol: "DE", name: "Deere & Company", sector: "Industrials", weight: 0.258331 },
  { symbol: "DELL", name: "Dell Technologies", sector: "Information Technology", weight: 0.235096 },
  { symbol: "DAL", name: "Delta Air Lines", sector: "Industrials", weight: 0.078175 },
  { symbol: "DVN", name: "Devon Energy", sector: "Energy", weight: 0.085629 },
  { symbol: "DXCM", name: "Dexcom", sector: "Health Care", weight: 0.049059 },
  { symbol: "FANG", name: "Diamondback Energy", sector: "Energy", weight: 0.059805 },
  { symbol: "DLR", name: "Digital Realty", sector: "Real Estate", weight: 0.09994 },
  { symbol: "DG", name: "Dollar General", sector: "Consumer Staples", weight: 0.041771 },
  { symbol: "DLTR", name: "Dollar Tree", sector: "Consumer Staples", weight: 0.032605 },
  { symbol: "D", name: "Dominion Energy", sector: "Utilities", weight: 0.087071 },
  { symbol: "DPZ", name: "Domino's", sector: "Consumer Discretionary", weight: 0.014968 },
  { symbol: "DASH", name: "DoorDash", sector: "Consumer Discretionary", weight: 0.113508 },
  { symbol: "DOV", name: "Dover Corporation", sector: "Industrials", weight: 0.039231 },
  { symbol: "DOW", name: "Dow Inc.", sector: "Materials", weight: 0.032112 },
  { symbol: "DHI", name: "D. R. Horton", sector: "Consumer Discretionary", weight: 0.055722 },
  { symbol: "DTE", name: "DTE Energy", sector: "Utilities", weight: 0.043047 },
  { symbol: "DUK", name: "Duke Energy", sector: "Utilities", weight: 0.142437 },
  { symbol: "DD", name: "DuPont", sector: "Industrials", weight: 0.026387 },
  { symbol: "ETN", name: "Eaton Corporation", sector: "Industrials", weight: 0.244862 },
  { symbol: "EBAY", name: "eBay Inc.", sector: "Consumer Discretionary", weight: 0.069888 },
  { symbol: "ECHO", name: "EchoStar", sector: "Communication Services", weight: 0.018762 },
  { symbol: "ECL", name: "Ecolab", sector: "Materials", weight: 0.10486 },
  { symbol: "EIX", name: "Edison International", sector: "Utilities", weight: 0.033613 },
  { symbol: "EW", name: "Edwards Lifesciences", sector: "Health Care", weight: 0.075466 },
  { symbol: "ELV", name: "Elevance Health", sector: "Health Care", weight: 0.130513 },
  { symbol: "EME", name: "Emcor", sector: "Industrials", weight: 0.050995 },
  { symbol: "EMR", name: "Emerson Electric", sector: "Industrials", weight: 0.128065 },
  { symbol: "ETR", name: "Entergy", sector: "Utilities", weight: 0.074622 },
  { symbol: "EOG", name: "EOG Resources", sector: "Energy", weight: 0.119082 },
  { symbol: "EQT", name: "EQT Corporation", sector: "Energy", weight: 0.051961 },
  { symbol: "EFX", name: "Equifax", sector: "Industrials", weight: 0.030437 },
  { symbol: "EQIX", name: "Equinix", sector: "Real Estate", weight: 0.156287 },
  { symbol: "ERIE", name: "Erie Indemnity", sector: "Financials", weight: 0.009415 },
  { symbol: "ESS", name: "Essex Property Trust", sector: "Real Estate", weight: 0.026803 },
  {
    symbol: "EL",
    name: "Estée Lauder Companies (The)",
    sector: "Consumer Staples",
    weight: 0.037027,
  },
  { symbol: "EG", name: "Everest Group", sector: "Financials", weight: 0.02214 },
  { symbol: "EVRG", name: "Evergy", sector: "Utilities", weight: 0.028477 },
  { symbol: "ES", name: "Eversource Energy", sector: "Utilities", weight: 0.040228 },
  { symbol: "EXC", name: "Exelon", sector: "Utilities", weight: 0.068 },
  { symbol: "EXE", name: "Expand Energy", sector: "Energy", weight: 0.035179 },
  { symbol: "EXPE", name: "Expedia Group", sector: "Consumer Discretionary", weight: 0.047457 },
  { symbol: "EXPD", name: "Expeditors International", sector: "Industrials", weight: 0.037458 },
  { symbol: "EXR", name: "Extra Space Storage", sector: "Real Estate", weight: 0.04357 },
  { symbol: "XOM", name: "ExxonMobil", sector: "Energy", weight: 1.034025 },
  { symbol: "FFIV", name: "F5, Inc.", sector: "Information Technology", weight: 0.034677 },
  { symbol: "FDS", name: "FactSet", sector: "Financials", weight: 0.015464 },
  { symbol: "FICO", name: "Fair Isaac", sector: "Information Technology", weight: 0.034632 },
  { symbol: "FAST", name: "Fastenal", sector: "Industrials", weight: 0.08518 },
  {
    symbol: "FRT",
    name: "Federal Realty Investment Trust",
    sector: "Real Estate",
    weight: 0.013814,
  },
  { symbol: "FDX", name: "FedEx", sector: "Industrials", weight: 0.103211 },
  { symbol: "FDXF", name: "FedEx Freight", sector: "Industrials", weight: 0.020567 },
  { symbol: "FERG", name: "Ferguson Enterprises", sector: "Industrials", weight: 0.065485 },
  {
    symbol: "FIS",
    name: "Fidelity National Information Services",
    sector: "Financials",
    weight: 0.029926,
  },
  { symbol: "FITB", name: "Fifth Third Bancorp", sector: "Financials", weight: 0.074509 },
  { symbol: "FSLR", name: "First Solar", sector: "Information Technology", weight: 0.033159 },
  { symbol: "FE", name: "FirstEnergy", sector: "Utilities", weight: 0.036583 },
  { symbol: "FISV", name: "Fiserv", sector: "Financials", weight: 0.039452 },
  { symbol: "FLEX", name: "Flex Ltd.", sector: "Information Technology", weight: 0.063003 },
  { symbol: "F", name: "Ford Motor Company", sector: "Consumer Discretionary", weight: 0.080054 },
  { symbol: "FTNT", name: "Fortinet", sector: "Information Technology", weight: 0.14854 },
  { symbol: "FTV", name: "Fortive", sector: "Industrials", weight: 0.025876 },
  {
    symbol: "FOXA",
    name: "Fox Corporation (Class A)",
    sector: "Communication Services",
    weight: 0.019375,
  },
  {
    symbol: "FOX",
    name: "Fox Corporation (Class B)",
    sector: "Communication Services",
    weight: 0.012147,
  },
  { symbol: "BEN", name: "Franklin Resources", sector: "Financials", weight: 0.01591 },
  { symbol: "FCX", name: "Freeport-McMoRan", sector: "Materials", weight: 0.166652 },
  { symbol: "GRMN", name: "Garmin", sector: "Consumer Discretionary", weight: 0.067617 },
  { symbol: "IT", name: "Gartner", sector: "Information Technology", weight: 0.017281 },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrials", weight: 0.51566 },
  { symbol: "GEHC", name: "GE HealthCare", sector: "Health Care", weight: 0.045086 },
  { symbol: "GEV", name: "GE Vernova", sector: "Industrials", weight: 0.388379 },
  { symbol: "GEN", name: "Gen Digital", sector: "Information Technology", weight: 0.024807 },
  { symbol: "GNRC", name: "Generac", sector: "Industrials", weight: 0.016539 },
  { symbol: "GD", name: "General Dynamics", sector: "Industrials", weight: 0.136127 },
  { symbol: "GIS", name: "General Mills", sector: "Consumer Staples", weight: 0.030101 },
  { symbol: "GM", name: "General Motors", sector: "Consumer Discretionary", weight: 0.114855 },
  {
    symbol: "GPC",
    name: "Genuine Parts Company",
    sector: "Consumer Discretionary",
    weight: 0.028308,
  },
  { symbol: "GILD", name: "Gilead Sciences", sector: "Health Care", weight: 0.274624 },
  { symbol: "GPN", name: "Global Payments", sector: "Financials", weight: 0.030772 },
  { symbol: "GL", name: "Globe Life", sector: "Financials", weight: 0.020052 },
  { symbol: "GDDY", name: "GoDaddy", sector: "Information Technology", weight: 0.01885 },
  { symbol: "GS", name: "Goldman Sachs", sector: "Financials", weight: 0.46087 },
  { symbol: "HAL", name: "Halliburton", sector: "Energy", weight: 0.047156 },
  { symbol: "HIG", name: "Hartford (The)", sector: "Financials", weight: 0.056931 },
  { symbol: "HAS", name: "Hasbro", sector: "Consumer Discretionary", weight: 0.018048 },
  { symbol: "HCA", name: "HCA Healthcare", sector: "Health Care", weight: 0.099617 },
  { symbol: "DOC", name: "Healthpeak Properties", sector: "Real Estate", weight: 0.021461 },
  { symbol: "HSIC", name: "Henry Schein", sector: "Health Care", weight: 0.012953 },
  { symbol: "HSY", name: "Hershey Company (The)", sector: "Consumer Staples", weight: 0.038885 },
  {
    symbol: "HPE",
    name: "Hewlett Packard Enterprise",
    sector: "Information Technology",
    weight: 0.118811,
  },
  { symbol: "HLT", name: "Hilton Worldwide", sector: "Consumer Discretionary", weight: 0.106281 },
  { symbol: "HD", name: "Home Depot (The)", sector: "Consumer Discretionary", weight: 0.469575 },
  { symbol: "HONA", name: "Honeywell Aerospace", sector: "Industrials", weight: 0.073034 },
  { symbol: "HON", name: "Honeywell Technologies", sector: "Industrials", weight: 0.09874 },
  { symbol: "HRL", name: "Hormel Foods", sector: "Consumer Staples", weight: 0.009301 },
  { symbol: "HST", name: "Host Hotels & Resorts", sector: "Real Estate", weight: 0.021348 },
  { symbol: "HWM", name: "Howmet Aerospace", sector: "Industrials", weight: 0.141241 },
  { symbol: "HPQ", name: "HP Inc.", sector: "Information Technology", weight: 0.045077 },
  { symbol: "HUBB", name: "Hubbell Incorporated", sector: "Industrials", weight: 0.036579 },
  { symbol: "HUM", name: "Humana", sector: "Health Care", weight: 0.073056 },
  { symbol: "HBAN", name: "Huntington Bancshares", sector: "Financials", weight: 0.051266 },
  { symbol: "HII", name: "Huntington Ingalls Industries", sector: "Industrials", weight: 0.016751 },
  { symbol: "IBM", name: "IBM", sector: "Information Technology", weight: 0.342421 },
  { symbol: "IEX", name: "IDEX Corporation", sector: "Industrials", weight: 0.025338 },
  { symbol: "IDXX", name: "Idexx Laboratories", sector: "Health Care", weight: 0.061812 },
  { symbol: "ITW", name: "Illinois Tool Works", sector: "Industrials", weight: 0.105113 },
  { symbol: "INCY", name: "Incyte", sector: "Health Care", weight: 0.031934 },
  { symbol: "IR", name: "Ingersoll Rand", sector: "Industrials", weight: 0.039808 },
  { symbol: "PODD", name: "Insulet Corporation", sector: "Health Care", weight: 0.014526 },
  { symbol: "INTC", name: "Intel", sector: "Information Technology", weight: 0.796974 },
  { symbol: "IBKR", name: "Interactive Brokers", sector: "Financials", weight: 0.06116 },
  { symbol: "ICE", name: "Intercontinental Exchange", sector: "Financials", weight: 0.134598 },
  {
    symbol: "IFF",
    name: "International Flavors & Fragrances",
    sector: "Materials",
    weight: 0.032811,
  },
  { symbol: "IP", name: "International Paper", sector: "Materials", weight: 0.027834 },
  { symbol: "INTU", name: "Intuit", sector: "Information Technology", weight: 0.132023 },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Health Care", weight: 0.18989 },
  { symbol: "IVZ", name: "Invesco", sector: "Financials", weight: 0.02168 },
  { symbol: "INVH", name: "Invitation Homes", sector: "Real Estate", weight: 0.023422 },
  { symbol: "IQV", name: "IQVIA", sector: "Health Care", weight: 0.065232 },
  { symbol: "IRM", name: "Iron Mountain", sector: "Real Estate", weight: 0.052128 },
  { symbol: "JBHT", name: "J.B. Hunt", sector: "Industrials", weight: 0.030322 },
  { symbol: "JBL", name: "Jabil", sector: "Information Technology", weight: 0.049956 },
  { symbol: "JKHY", name: "Jack Henry & Associates", sector: "Financials", weight: 0.01712 },
  { symbol: "J", name: "Jacobs Solutions", sector: "Industrials", weight: 0.025448 },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Health Care", weight: 0.976585 },
  { symbol: "JCI", name: "Johnson Controls", sector: "Industrials", weight: 0.134466 },
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Financials", weight: 1.443834 },
  { symbol: "KVUE", name: "Kenvue", sector: "Consumer Staples", weight: 0.051828 },
  { symbol: "KDP", name: "Keurig Dr Pepper", sector: "Consumer Staples", weight: 0.066376 },
  { symbol: "KEY", name: "KeyCorp", sector: "Financials", weight: 0.030455 },
  {
    symbol: "KEYS",
    name: "Keysight Technologies",
    sector: "Information Technology",
    weight: 0.086124,
  },
  { symbol: "KMB", name: "Kimberly-Clark", sector: "Consumer Staples", weight: 0.049819 },
  { symbol: "KIM", name: "Kimco Realty", sector: "Real Estate", weight: 0.024174 },
  { symbol: "KMI", name: "Kinder Morgan", sector: "Energy", weight: 0.09352 },
  { symbol: "KKR", name: "KKR & Co.", sector: "Financials", weight: 0.109442 },
  { symbol: "KLAC", name: "KLA Corporation", sector: "Information Technology", weight: 0.362958 },
  { symbol: "KHC", name: "Kraft Heinz", sector: "Consumer Staples", weight: 0.032053 },
  { symbol: "KR", name: "Kroger", sector: "Consumer Staples", weight: 0.048689 },
  { symbol: "LHX", name: "L3Harris", sector: "Industrials", weight: 0.070945 },
  { symbol: "LH", name: "Labcorp", sector: "Health Care", weight: 0.040057 },
  { symbol: "LRCX", name: "Lam Research", sector: "Information Technology", weight: 0.600105 },
  { symbol: "LVS", name: "Las Vegas Sands", sector: "Consumer Discretionary", weight: 0.019648 },
  { symbol: "LDOS", name: "Leidos", sector: "Industrials", weight: 0.024513 },
  { symbol: "LEN", name: "Lennar", sector: "Consumer Discretionary", weight: 0.026438 },
  { symbol: "LII", name: "Lennox International", sector: "Industrials", weight: 0.018084 },
  { symbol: "LLY", name: "Lilly (Eli)", sector: "Health Care", weight: 1.35096 },
  { symbol: "LIN", name: "Linde plc", sector: "Materials", weight: 0.327599 },
  {
    symbol: "LYV",
    name: "Live Nation Entertainment",
    sector: "Communication Services",
    weight: 0.040913,
  },
  { symbol: "LMT", name: "Lockheed Martin", sector: "Industrials", weight: 0.161595 },
  { symbol: "L", name: "Loews Corporation", sector: "Financials", weight: 0.027889 },
  { symbol: "LOW", name: "Lowe's", sector: "Consumer Discretionary", weight: 0.168805 },
  {
    symbol: "LULU",
    name: "Lululemon Athletica",
    sector: "Consumer Discretionary",
    weight: 0.015883,
  },
  { symbol: "LITE", name: "Lumentum", sector: "Information Technology", weight: 0.117 },
  { symbol: "LYB", name: "LyondellBasell", sector: "Materials", weight: 0.025425 },
  { symbol: "MTB", name: "M&T Bank", sector: "Financials", weight: 0.053007 },
  { symbol: "MPC", name: "Marathon Petroleum", sector: "Energy", weight: 0.176935 },
  {
    symbol: "MAR",
    name: "Marriott International",
    sector: "Consumer Discretionary",
    weight: 0.110346,
  },
  { symbol: "MRSH", name: "Marsh McLennan", sector: "Financials", weight: 0.129565 },
  { symbol: "MLM", name: "Martin Marietta Materials", sector: "Materials", weight: 0.045939 },
  {
    symbol: "MRVL",
    name: "Marvell Technology",
    sector: "Information Technology",
    weight: 0.312402,
  },
  { symbol: "MAS", name: "Masco", sector: "Industrials", weight: 0.021355 },
  { symbol: "MA", name: "Mastercard", sector: "Financials", weight: 0.695492 },
  { symbol: "MKC", name: "McCormick & Company", sector: "Consumer Staples", weight: 0.019945 },
  { symbol: "MCD", name: "McDonald's", sector: "Consumer Discretionary", weight: 0.27354 },
  { symbol: "MCK", name: "McKesson Corporation", sector: "Health Care", weight: 0.162706 },
  { symbol: "MDT", name: "Medtronic", sector: "Health Care", weight: 0.179037 },
  { symbol: "MRK", name: "Merck & Co.", sector: "Health Care", weight: 0.553564 },
  { symbol: "META", name: "Meta Platforms", sector: "Communication Services", weight: 2.180822 },
  { symbol: "MET", name: "MetLife", sector: "Financials", weight: 0.078649 },
  { symbol: "MTD", name: "Mettler Toledo", sector: "Health Care", weight: 0.03944 },
  { symbol: "MGM", name: "MGM Resorts", sector: "Consumer Discretionary", weight: 0.011728 },
  {
    symbol: "MCHP",
    name: "Microchip Technology",
    sector: "Information Technology",
    weight: 0.060087,
  },
  { symbol: "MU", name: "Micron Technology", sector: "Information Technology", weight: 1.760742 },
  { symbol: "MSFT", name: "Microsoft", sector: "Information Technology", weight: 5.548225 },
  {
    symbol: "MAA",
    name: "Mid-America Apartment Communities",
    sector: "Real Estate",
    weight: 0.022557,
  },
  { symbol: "MRNA", name: "Moderna", sector: "Health Care", weight: 0.072835 },
  {
    symbol: "TAP",
    name: "Molson Coors Beverage Company",
    sector: "Consumer Staples",
    weight: 0.009388,
  },
  { symbol: "MDLZ", name: "Mondelez International", sector: "Consumer Staples", weight: 0.121535 },
  {
    symbol: "MPWR",
    name: "Monolithic Power Systems",
    sector: "Information Technology",
    weight: 0.089882,
  },
  { symbol: "MNST", name: "Monster Beverage", sector: "Consumer Staples", weight: 0.092977 },
  { symbol: "MCO", name: "Moody's Corporation", sector: "Financials", weight: 0.108428 },
  { symbol: "MS", name: "Morgan Stanley", sector: "Financials", weight: 0.392004 },
  { symbol: "MOS", name: "Mosaic Company (The)", sector: "Materials", weight: 0.012653 },
  { symbol: "MSI", name: "Motorola Solutions", sector: "Information Technology", weight: 0.116058 },
  { symbol: "MSCI", name: "MSCI", sector: "Financials", weight: 0.061384 },
  { symbol: "NDAQ", name: "Nasdaq, Inc.", sector: "Financials", weight: 0.064017 },
  { symbol: "NTAP", name: "NetApp", sector: "Information Technology", weight: 0.055515 },
  { symbol: "NFLX", name: "Netflix", sector: "Communication Services", weight: 0.486171 },
  { symbol: "NEM", name: "Newmont", sector: "Materials", weight: 0.208538 },
  {
    symbol: "NWSA",
    name: "News Corp (Class A)",
    sector: "Communication Services",
    weight: 0.01643,
  },
  {
    symbol: "NWS",
    name: "News Corp (Class B)",
    sector: "Communication Services",
    weight: 0.006136,
  },
  { symbol: "NEE", name: "NextEra Energy", sector: "Utilities", weight: 0.261757 },
  { symbol: "NKE", name: "Nike, Inc.", sector: "Consumer Discretionary", weight: 0.068133 },
  { symbol: "NI", name: "NiSource", sector: "Utilities", weight: 0.030297 },
  { symbol: "NDSN", name: "Nordson Corporation", sector: "Industrials", weight: 0.025234 },
  { symbol: "NSC", name: "Norfolk Southern", sector: "Industrials", weight: 0.110162 },
  { symbol: "NTRS", name: "Northern Trust", sector: "Financials", weight: 0.051969 },
  { symbol: "NOC", name: "Northrop Grumman", sector: "Industrials", weight: 0.104662 },
  {
    symbol: "NCLH",
    name: "Norwegian Cruise Line Holdings",
    sector: "Consumer Discretionary",
    weight: 0.01044,
  },
  { symbol: "NRG", name: "NRG Energy", sector: "Utilities", weight: 0.037014 },
  { symbol: "NUE", name: "Nucor", sector: "Materials", weight: 0.089326 },
  { symbol: "NVDA", name: "Nvidia", sector: "Information Technology", weight: 8.220761 },
  { symbol: "NVR", name: "NVR, Inc.", sector: "Consumer Discretionary", weight: 0.025306 },
  {
    symbol: "NXPI",
    name: "NXP Semiconductors",
    sector: "Information Technology",
    weight: 0.085758,
  },
  {
    symbol: "ORLY",
    name: "O'Reilly Automotive",
    sector: "Consumer Discretionary",
    weight: 0.108481,
  },
  { symbol: "OXY", name: "Occidental Petroleum", sector: "Energy", weight: 0.06738 },
  { symbol: "ODFL", name: "Old Dominion", sector: "Industrials", weight: 0.050641 },
  { symbol: "OMC", name: "Omnicom Group", sector: "Communication Services", weight: 0.033935 },
  { symbol: "ON", name: "ON Semiconductor", sector: "Information Technology", weight: 0.042302 },
  { symbol: "OKE", name: "Oneok", sector: "Energy", weight: 0.091806 },
  {
    symbol: "ORCL",
    name: "Oracle Corporation",
    sector: "Information Technology",
    weight: 0.416796,
  },
  { symbol: "OTIS", name: "Otis Worldwide", sector: "Industrials", weight: 0.040436 },
  { symbol: "PCAR", name: "Paccar", sector: "Industrials", weight: 0.097546 },
  {
    symbol: "PKG",
    name: "Packaging Corporation of America",
    sector: "Materials",
    weight: 0.030596,
  },
  {
    symbol: "PLTR",
    name: "Palantir Technologies",
    sector: "Information Technology",
    weight: 0.591157,
  },
  {
    symbol: "PANW",
    name: "Palo Alto Networks",
    sector: "Information Technology",
    weight: 0.412718,
  },
  {
    symbol: "PSKY",
    name: "Paramount Skydance Corporation",
    sector: "Communication Services",
    weight: 0.004884,
  },
  { symbol: "PH", name: "Parker Hannifin", sector: "Industrials", weight: 0.181699 },
  { symbol: "PAYX", name: "Paychex", sector: "Industrials", weight: 0.056282 },
  { symbol: "PYPL", name: "PayPal", sector: "Financials", weight: 0.069983 },
  { symbol: "PNR", name: "Pentair", sector: "Industrials", weight: 0.014138 },
  { symbol: "PEP", name: "PepsiCo", sector: "Consumer Staples", weight: 0.283746 },
  { symbol: "PFE", name: "Pfizer", sector: "Health Care", weight: 0.240342 },
  { symbol: "PCG", name: "PG&E Corporation", sector: "Utilities", weight: 0.047523 },
  {
    symbol: "PM",
    name: "Philip Morris International",
    sector: "Consumer Staples",
    weight: 0.439552,
  },
  { symbol: "PSX", name: "Phillips 66", sector: "Energy", weight: 0.158995 },
  { symbol: "PNW", name: "Pinnacle West Capital", sector: "Utilities", weight: 0.01792 },
  { symbol: "PNC", name: "PNC Financial Services", sector: "Financials", weight: 0.146664 },
  { symbol: "PPG", name: "PPG Industries", sector: "Materials", weight: 0.036322 },
  { symbol: "PPL", name: "PPL Corporation", sector: "Utilities", weight: 0.039204 },
  { symbol: "PFG", name: "Principal Financial Group", sector: "Financials", weight: 0.034073 },
  { symbol: "PG", name: "Procter & Gamble", sector: "Consumer Staples", weight: 0.504405 },
  { symbol: "PGR", name: "Progressive Corporation", sector: "Financials", weight: 0.19111 },
  { symbol: "PLD", name: "Prologis", sector: "Real Estate", weight: 0.195211 },
  { symbol: "PRU", name: "Prudential Financial", sector: "Financials", weight: 0.062051 },
  { symbol: "PEG", name: "Public Service Enterprise Group", sector: "Utilities", weight: 0.055019 },
  { symbol: "PTC", name: "PTC Inc.", sector: "Information Technology", weight: 0.022641 },
  { symbol: "PSA", name: "Public Storage", sector: "Real Estate", weight: 0.075138 },
  { symbol: "PHM", name: "PulteGroup", sector: "Consumer Discretionary", weight: 0.034447 },
  { symbol: "PWR", name: "Quanta Services", sector: "Industrials", weight: 0.142756 },
  { symbol: "QCOM", name: "Qualcomm", sector: "Information Technology", weight: 0.282359 },
  { symbol: "DGX", name: "Quest Diagnostics", sector: "Health Care", weight: 0.039634 },
  { symbol: "Q", name: "Qnity Electronics", sector: "Information Technology", weight: 0.039917 },
  {
    symbol: "RL",
    name: "Ralph Lauren Corporation",
    sector: "Consumer Discretionary",
    weight: 0.019778,
  },
  { symbol: "RJF", name: "Raymond James Financial", sector: "Financials", weight: 0.046291 },
  { symbol: "RDDT", name: "Reddit", sector: "Communication Services", weight: 0.028991 },
  { symbol: "RTX", name: "RTX Corporation", sector: "Industrials", weight: 0.404155 },
  { symbol: "O", name: "Realty Income", sector: "Real Estate", weight: 0.085239 },
  { symbol: "REG", name: "Regency Centers", sector: "Real Estate", weight: 0.018881 },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", sector: "Health Care", weight: 0.122735 },
  { symbol: "RF", name: "Regions Financial Corporation", sector: "Financials", weight: 0.038791 },
  { symbol: "RSG", name: "Republic Services", sector: "Industrials", weight: 0.067659 },
  { symbol: "RMD", name: "ResMed", sector: "Health Care", weight: 0.048518 },
  { symbol: "RVTY", name: "Revvity", sector: "Health Care", weight: 0.021016 },
  { symbol: "HOOD", name: "Robinhood Markets", sector: "Financials", weight: 0.138374 },
  { symbol: "ROK", name: "Rockwell Automation", sector: "Industrials", weight: 0.07208 },
  { symbol: "ROL", name: "Rollins, Inc.", sector: "Industrials", weight: 0.015428 },
  { symbol: "ROP", name: "Roper Technologies", sector: "Information Technology", weight: 0.059888 },
  { symbol: "ROST", name: "Ross Stores", sector: "Consumer Discretionary", weight: 0.110368 },
  {
    symbol: "RCL",
    name: "Royal Caribbean Group",
    sector: "Consumer Discretionary",
    weight: 0.098548,
  },
  { symbol: "SPGI", name: "S&P Global", sector: "Financials", weight: 0.192514 },
  { symbol: "CRM", name: "Salesforce", sector: "Information Technology", weight: 0.303317 },
  { symbol: "SNDK", name: "Sandisk", sector: "Information Technology", weight: 0.397044 },
  { symbol: "SBAC", name: "SBA Communications", sector: "Real Estate", weight: 0.030111 },
  { symbol: "SLB", name: "Schlumberger", sector: "Energy", weight: 0.129707 },
  { symbol: "STX", name: "Seagate Technology", sector: "Information Technology", weight: 0.30162 },
  { symbol: "SRE", name: "Sempra", sector: "Utilities", weight: 0.084511 },
  { symbol: "NOW", name: "ServiceNow", sector: "Information Technology", weight: 0.205299 },
  { symbol: "SHW", name: "Sherwin-Williams", sector: "Materials", weight: 0.111847 },
  { symbol: "SPG", name: "Simon Property Group", sector: "Real Estate", weight: 0.100865 },
  {
    symbol: "SWKS",
    name: "Skyworks Solutions",
    sector: "Information Technology",
    weight: 0.017505,
  },
  {
    symbol: "SJM",
    name: "J.M. Smucker Company (The)",
    sector: "Consumer Staples",
    weight: 0.020002,
  },
  { symbol: "SW", name: "Smurfit Westrock", sector: "Materials", weight: 0.033681 },
  { symbol: "SNA", name: "Snap-on", sector: "Industrials", weight: 0.029732 },
  { symbol: "SOLV", name: "Solventum", sector: "Health Care", weight: 0.020151 },
  { symbol: "SO", name: "Southern Company", sector: "Utilities", weight: 0.151107 },
  { symbol: "LUV", name: "Southwest Airlines", sector: "Industrials", weight: 0.028742 },
  { symbol: "SWK", name: "Stanley Black & Decker", sector: "Industrials", weight: 0.021673 },
  { symbol: "SBUX", name: "Starbucks", sector: "Consumer Discretionary", weight: 0.173036 },
  { symbol: "STT", name: "State Street Corporation", sector: "Financials", weight: 0.080758 },
  { symbol: "STLD", name: "Steel Dynamics", sector: "Materials", weight: 0.049635 },
  { symbol: "STE", name: "Steris", sector: "Health Care", weight: 0.032083 },
  { symbol: "SYK", name: "Stryker Corporation", sector: "Health Care", weight: 0.144193 },
  { symbol: "SMCI", name: "Supermicro", sector: "Information Technology", weight: 0.033316 },
  { symbol: "SYF", name: "Synchrony Financial", sector: "Financials", weight: 0.039567 },
  { symbol: "SNPS", name: "Synopsys", sector: "Information Technology", weight: 0.114552 },
  { symbol: "SYY", name: "Sysco", sector: "Consumer Staples", weight: 0.059316 },
  { symbol: "TMUS", name: "T-Mobile US", sector: "Communication Services", weight: 0.125508 },
  { symbol: "TROW", name: "T. Rowe Price", sector: "Financials", weight: 0.035105 },
  {
    symbol: "TTWO",
    name: "Take-Two Interactive",
    sector: "Communication Services",
    weight: 0.055893,
  },
  { symbol: "TPR", name: "Tapestry, Inc.", sector: "Consumer Discretionary", weight: 0.034993 },
  { symbol: "TRGP", name: "Targa Resources", sector: "Energy", weight: 0.095102 },
  { symbol: "TGT", name: "Target Corporation", sector: "Consumer Staples", weight: 0.108601 },
  { symbol: "TEL", name: "TE Connectivity", sector: "Information Technology", weight: 0.090855 },
  {
    symbol: "TDY",
    name: "Teledyne Technologies",
    sector: "Information Technology",
    weight: 0.041945,
  },
  { symbol: "TER", name: "Teradyne", sector: "Information Technology", weight: 0.09131 },
  { symbol: "TSLA", name: "Tesla, Inc.", sector: "Consumer Discretionary", weight: 1.573025 },
  { symbol: "TXN", name: "Texas Instruments", sector: "Information Technology", weight: 0.361642 },
  { symbol: "TPL", name: "Texas Pacific Land Corporation", sector: "Energy", weight: 0.032946 },
  { symbol: "TXT", name: "Textron", sector: "Industrials", weight: 0.021081 },
  { symbol: "TMO", name: "Thermo Fisher Scientific", sector: "Health Care", weight: 0.341894 },
  { symbol: "TJX", name: "TJX Companies", sector: "Consumer Discretionary", weight: 0.211802 },
  { symbol: "TKO", name: "TKO Group Holdings", sector: "Communication Services", weight: 0.01829 },
  { symbol: "TTD", name: "Trade Desk (The)", sector: "Communication Services", weight: 0.009013 },
  { symbol: "TSCO", name: "Tractor Supply", sector: "Consumer Discretionary", weight: 0.027117 },
  { symbol: "TT", name: "Trane Technologies", sector: "Industrials", weight: 0.148971 },
  { symbol: "TDG", name: "TransDigm Group", sector: "Industrials", weight: 0.095707 },
  { symbol: "TRV", name: "Travelers Companies (The)", sector: "Financials", weight: 0.118219 },
  { symbol: "TRMB", name: "Trimble Inc.", sector: "Information Technology", weight: 0.020348 },
  { symbol: "TFC", name: "Truist Financial", sector: "Financials", weight: 0.095018 },
  { symbol: "TYL", name: "Tyler Technologies", sector: "Information Technology", weight: 0.02196 },
  { symbol: "TSN", name: "Tyson Foods", sector: "Consumer Staples", weight: 0.022199 },
  { symbol: "USB", name: "U.S. Bancorp", sector: "Financials", weight: 0.146288 },
  { symbol: "UBER", name: "Uber", sector: "Industrials", weight: 0.219724 },
  { symbol: "UDR", name: "UDR, Inc.", sector: "Real Estate", weight: 0.015916 },
  { symbol: "ULTA", name: "Ulta Beauty", sector: "Consumer Discretionary", weight: 0.035883 },
  { symbol: "UNP", name: "Union Pacific Corporation", sector: "Industrials", weight: 0.256741 },
  { symbol: "UAL", name: "United Airlines Holdings", sector: "Industrials", weight: 0.052872 },
  { symbol: "UPS", name: "United Parcel Service", sector: "Industrials", weight: 0.112655 },
  { symbol: "URI", name: "United Rentals", sector: "Industrials", weight: 0.09798 },
  { symbol: "UNH", name: "UnitedHealth Group", sector: "Health Care", weight: 0.542126 },
  { symbol: "UHS", name: "Universal Health Services", sector: "Health Care", weight: 0.014248 },
  { symbol: "VLO", name: "Valero Energy", sector: "Energy", weight: 0.175229 },
  { symbol: "VEEV", name: "Veeva Systems", sector: "Health Care", weight: 0.059547 },
  { symbol: "VTR", name: "Ventas", sector: "Real Estate", weight: 0.066086 },
  { symbol: "VLTO", name: "Veralto", sector: "Industrials", weight: 0.035374 },
  { symbol: "VRSN", name: "Verisign", sector: "Information Technology", weight: 0.035724 },
  { symbol: "VRSK", name: "Verisk Analytics", sector: "Industrials", weight: 0.035466 },
  { symbol: "VZ", name: "Verizon", sector: "Communication Services", weight: 0.315449 },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", sector: "Health Care", weight: 0.200738 },
  { symbol: "VRT", name: "Vertiv", sector: "Industrials", weight: 0.153475 },
  { symbol: "VTRS", name: "Viatris", sector: "Health Care", weight: 0.02919 },
  { symbol: "VICI", name: "Vici Properties", sector: "Real Estate", weight: 0.041853 },
  { symbol: "V", name: "Visa Inc.", sector: "Financials", weight: 0.926149 },
  { symbol: "VST", name: "Vistra Corp.", sector: "Utilities", weight: 0.072836 },
  { symbol: "VMRK", name: "Vivmark Residential", sector: "Real Estate", weight: 0.071951 },
  { symbol: "VMC", name: "Vulcan Materials Company", sector: "Materials", weight: 0.049305 },
  { symbol: "WRB", name: "W. R. Berkley Corporation", sector: "Financials", weight: 0.031264 },
  { symbol: "GWW", name: "W. W. Grainger", sector: "Industrials", weight: 0.084452 },
  { symbol: "WAB", name: "Wabtec", sector: "Industrials", weight: 0.072361 },
  { symbol: "WMT", name: "Walmart", sector: "Consumer Staples", weight: 0.704719 },
  {
    symbol: "DIS",
    name: "Walt Disney Company (The)",
    sector: "Communication Services",
    weight: 0.274753,
  },
  {
    symbol: "WBD",
    name: "Warner Bros. Discovery",
    sector: "Communication Services",
    weight: 0.105193,
  },
  { symbol: "WM", name: "Waste Management", sector: "Industrials", weight: 0.121603 },
  { symbol: "WAT", name: "Waters Corporation", sector: "Health Care", weight: 0.060367 },
  { symbol: "WEC", name: "WEC Energy Group", sector: "Utilities", weight: 0.052584 },
  { symbol: "WFC", name: "Wells Fargo", sector: "Financials", weight: 0.416704 },
  { symbol: "WELL", name: "Welltower", sector: "Real Estate", weight: 0.252881 },
  { symbol: "WST", name: "West Pharmaceutical Services", sector: "Health Care", weight: 0.0362 },
  { symbol: "WDC", name: "Western Digital", sector: "Information Technology", weight: 0.252363 },
  { symbol: "WY", name: "Weyerhaeuser", sector: "Real Estate", weight: 0.024584 },
  {
    symbol: "WSM",
    name: "Williams-Sonoma, Inc.",
    sector: "Consumer Discretionary",
    weight: 0.040735,
  },
  { symbol: "WMB", name: "Williams Companies", sector: "Energy", weight: 0.139531 },
  { symbol: "WTW", name: "Willis Towers Watson", sector: "Financials", weight: 0.045069 },
  { symbol: "WDAY", name: "Workday, Inc.", sector: "Information Technology", weight: 0.057635 },
  { symbol: "WYNN", name: "Wynn Resorts", sector: "Consumer Discretionary", weight: 0.011504 },
  { symbol: "XEL", name: "Xcel Energy", sector: "Utilities", weight: 0.072334 },
  { symbol: "XYL", name: "Xylem Inc.", sector: "Industrials", weight: 0.038911 },
  { symbol: "YUM", name: "Yum! Brands", sector: "Consumer Discretionary", weight: 0.060848 },
  {
    symbol: "ZBRA",
    name: "Zebra Technologies",
    sector: "Information Technology",
    weight: 0.024992,
  },
  { symbol: "ZBH", name: "Zimmer Biomet", sector: "Health Care", weight: 0.027834 },
  { symbol: "ZTS", name: "Zoetis", sector: "Health Care", weight: 0.046739 },
];
